package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* JADX INFO: compiled from: com.android.billingclient:billing@@9.1.0 */
/* JADX INFO: loaded from: classes.dex */
final class zzdh {
    static final BillingResult zzA;
    static final BillingResult zzB;
    static final BillingResult zzC;
    static final BillingResult zzD;
    static final BillingResult zzE;
    static final BillingResult zzF;
    static final BillingResult zzG;
    static final BillingResult zzH;
    static final BillingResult zzI;
    static final BillingResult zzJ;
    static final BillingResult zzK;
    public static final /* synthetic */ int zzL = 0;
    static final BillingResult zza;
    static final BillingResult zzb;
    static final BillingResult zzc;
    static final BillingResult zzd;
    static final BillingResult zze;
    static final BillingResult zzf;
    static final BillingResult zzg;
    static final BillingResult zzh;
    static final BillingResult zzi;
    static final BillingResult zzj;
    static final BillingResult zzk;
    static final BillingResult zzl;
    static final BillingResult zzm;
    static final BillingResult zzn;
    static final BillingResult zzo;
    static final BillingResult zzp;
    static final BillingResult zzq;
    static final BillingResult zzr;
    static final BillingResult zzs;
    static final BillingResult zzt;
    static final BillingResult zzu;
    static final BillingResult zzv;
    static final BillingResult zzw;
    static final BillingResult zzx;
    static final BillingResult zzy;
    static final BillingResult zzz;

    static {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.setResponseCode(3);
        builderNewBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        builderNewBuilder.build();
        BillingResult.Builder builderNewBuilder2 = BillingResult.newBuilder();
        builderNewBuilder2.setResponseCode(3);
        builderNewBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        zza = builderNewBuilder2.build();
        BillingResult.Builder builderNewBuilder3 = BillingResult.newBuilder();
        builderNewBuilder3.setResponseCode(3);
        builderNewBuilder3.setDebugMessage("Billing service unavailable on device.");
        zzb = builderNewBuilder3.build();
        BillingResult.Builder builderNewBuilder4 = BillingResult.newBuilder();
        builderNewBuilder4.setResponseCode(2);
        builderNewBuilder4.setDebugMessage("Billing service unavailable on device.");
        zzc = builderNewBuilder4.build();
        BillingResult.Builder builderNewBuilder5 = BillingResult.newBuilder();
        builderNewBuilder5.setResponseCode(5);
        builderNewBuilder5.setDebugMessage("Client is already in the process of connecting to billing service.");
        zzd = builderNewBuilder5.build();
        BillingResult.Builder builderNewBuilder6 = BillingResult.newBuilder();
        builderNewBuilder6.setResponseCode(5);
        builderNewBuilder6.setDebugMessage("The list of SKUs can't be empty.");
        builderNewBuilder6.build();
        BillingResult.Builder builderNewBuilder7 = BillingResult.newBuilder();
        builderNewBuilder7.setResponseCode(5);
        builderNewBuilder7.setDebugMessage("SKU type can't be empty.");
        builderNewBuilder7.build();
        BillingResult.Builder builderNewBuilder8 = BillingResult.newBuilder();
        builderNewBuilder8.setResponseCode(5);
        builderNewBuilder8.setDebugMessage("Product type can't be empty.");
        zze = builderNewBuilder8.build();
        BillingResult.Builder builderNewBuilder9 = BillingResult.newBuilder();
        builderNewBuilder9.setResponseCode(-2);
        builderNewBuilder9.setDebugMessage("Client does not support extra params.");
        zzf = builderNewBuilder9.build();
        BillingResult.Builder builderNewBuilder10 = BillingResult.newBuilder();
        builderNewBuilder10.setResponseCode(5);
        builderNewBuilder10.setDebugMessage("Invalid purchase token.");
        zzg = builderNewBuilder10.build();
        BillingResult.Builder builderNewBuilder11 = BillingResult.newBuilder();
        builderNewBuilder11.setResponseCode(6);
        builderNewBuilder11.setDebugMessage("An internal error occurred.");
        zzh = builderNewBuilder11.build();
        BillingResult.Builder builderNewBuilder12 = BillingResult.newBuilder();
        builderNewBuilder12.setResponseCode(5);
        builderNewBuilder12.setDebugMessage("SKU can't be null.");
        builderNewBuilder12.build();
        BillingResult.Builder builderNewBuilder13 = BillingResult.newBuilder();
        builderNewBuilder13.setResponseCode(0);
        zzi = builderNewBuilder13.build();
        BillingResult.Builder builderNewBuilder14 = BillingResult.newBuilder();
        builderNewBuilder14.setResponseCode(-1);
        builderNewBuilder14.setDebugMessage("Service connection is disconnected.");
        zzj = builderNewBuilder14.build();
        BillingResult.Builder builderNewBuilder15 = BillingResult.newBuilder();
        builderNewBuilder15.setResponseCode(2);
        builderNewBuilder15.setDebugMessage("Timeout communicating with service.");
        zzk = builderNewBuilder15.build();
        BillingResult.Builder builderNewBuilder16 = BillingResult.newBuilder();
        builderNewBuilder16.setResponseCode(-2);
        builderNewBuilder16.setDebugMessage("Client does not support subscriptions.");
        zzl = builderNewBuilder16.build();
        BillingResult.Builder builderNewBuilder17 = BillingResult.newBuilder();
        builderNewBuilder17.setResponseCode(-2);
        builderNewBuilder17.setDebugMessage("Client does not support subscriptions update.");
        zzm = builderNewBuilder17.build();
        BillingResult.Builder builderNewBuilder18 = BillingResult.newBuilder();
        builderNewBuilder18.setResponseCode(-2);
        builderNewBuilder18.setDebugMessage("Client does not support get purchase history.");
        builderNewBuilder18.build();
        BillingResult.Builder builderNewBuilder19 = BillingResult.newBuilder();
        builderNewBuilder19.setResponseCode(-2);
        builderNewBuilder19.setDebugMessage("Client does not support price change confirmation.");
        zzn = builderNewBuilder19.build();
        BillingResult.Builder builderNewBuilder20 = BillingResult.newBuilder();
        builderNewBuilder20.setResponseCode(-2);
        builderNewBuilder20.setDebugMessage("Play Store version installed does not support cross selling products.");
        zzo = builderNewBuilder20.build();
        BillingResult.Builder builderNewBuilder21 = BillingResult.newBuilder();
        builderNewBuilder21.setResponseCode(-2);
        builderNewBuilder21.setDebugMessage("Client does not support multi-item purchases.");
        zzp = builderNewBuilder21.build();
        BillingResult.Builder builderNewBuilder22 = BillingResult.newBuilder();
        builderNewBuilder22.setResponseCode(-2);
        builderNewBuilder22.setDebugMessage("Client does not support offer_id_token.");
        zzq = builderNewBuilder22.build();
        BillingResult.Builder builderNewBuilder23 = BillingResult.newBuilder();
        builderNewBuilder23.setResponseCode(-2);
        builderNewBuilder23.setDebugMessage("Play Store version installed does not support gift code purchase.");
        zzr = builderNewBuilder23.build();
        BillingResult.Builder builderNewBuilder24 = BillingResult.newBuilder();
        builderNewBuilder24.setResponseCode(-2);
        builderNewBuilder24.setDebugMessage("Client does not support ProductDetails.");
        zzs = builderNewBuilder24.build();
        BillingResult.Builder builderNewBuilder25 = BillingResult.newBuilder();
        builderNewBuilder25.setResponseCode(-2);
        builderNewBuilder25.setDebugMessage("Client does not support launching subscription management action flow.");
        builderNewBuilder25.build();
        BillingResult.Builder builderNewBuilder26 = BillingResult.newBuilder();
        builderNewBuilder26.setResponseCode(-2);
        builderNewBuilder26.setDebugMessage("Client does not support in-app messages.");
        zzt = builderNewBuilder26.build();
        BillingResult.Builder builderNewBuilder27 = BillingResult.newBuilder();
        builderNewBuilder27.setResponseCode(-2);
        builderNewBuilder27.setDebugMessage("Client does not support user choice billing.");
        builderNewBuilder27.build();
        BillingResult.Builder builderNewBuilder28 = BillingResult.newBuilder();
        builderNewBuilder28.setResponseCode(-2);
        builderNewBuilder28.setDebugMessage("Play Store version installed does not support external offer.");
        zzu = builderNewBuilder28.build();
        BillingResult.Builder builderNewBuilder29 = BillingResult.newBuilder();
        builderNewBuilder29.setResponseCode(-2);
        builderNewBuilder29.setDebugMessage("Play Store version installed does not support multi-item purchases with season pass in one cart.");
        zzv = builderNewBuilder29.build();
        BillingResult.Builder builderNewBuilder30 = BillingResult.newBuilder();
        builderNewBuilder30.setResponseCode(-2);
        builderNewBuilder30.setDebugMessage("Play Store version installed does not support querying AutoPay plan purchase.");
        zzw = builderNewBuilder30.build();
        BillingResult.Builder builderNewBuilder31 = BillingResult.newBuilder();
        builderNewBuilder31.setResponseCode(-2);
        builderNewBuilder31.setDebugMessage("Play Store version installed does not support including suspended subscriptions.");
        zzx = builderNewBuilder31.build();
        BillingResult.Builder builderNewBuilder32 = BillingResult.newBuilder();
        builderNewBuilder32.setResponseCode(5);
        builderNewBuilder32.setDebugMessage("Unknown feature");
        zzy = builderNewBuilder32.build();
        BillingResult.Builder builderNewBuilder33 = BillingResult.newBuilder();
        builderNewBuilder33.setResponseCode(-2);
        builderNewBuilder33.setDebugMessage("Play Store version installed does not support get billing config.");
        zzz = builderNewBuilder33.build();
        BillingResult.Builder builderNewBuilder34 = BillingResult.newBuilder();
        builderNewBuilder34.setResponseCode(-2);
        builderNewBuilder34.setDebugMessage("Query product details with serialized docid is not supported.");
        zzA = builderNewBuilder34.build();
        BillingResult.Builder builderNewBuilder35 = BillingResult.newBuilder();
        builderNewBuilder35.setResponseCode(-2);
        builderNewBuilder35.setDebugMessage("Play Store version installed does not support launching external offer flow.");
        builderNewBuilder35.build();
        BillingResult.Builder builderNewBuilder36 = BillingResult.newBuilder();
        builderNewBuilder36.setResponseCode(4);
        builderNewBuilder36.setDebugMessage("Item is unavailable for purchase.");
        zzB = builderNewBuilder36.build();
        BillingResult.Builder builderNewBuilder37 = BillingResult.newBuilder();
        builderNewBuilder37.setResponseCode(-2);
        builderNewBuilder37.setDebugMessage("Query product details with developer specified account is not supported.");
        zzC = builderNewBuilder37.build();
        BillingResult.Builder builderNewBuilder38 = BillingResult.newBuilder();
        builderNewBuilder38.setResponseCode(-2);
        builderNewBuilder38.setDebugMessage("Play Store version installed does not support alternative billing only.");
        zzD = builderNewBuilder38.build();
        BillingResult.Builder builderNewBuilder39 = BillingResult.newBuilder();
        builderNewBuilder39.setResponseCode(5);
        builderNewBuilder39.setDebugMessage("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        zzE = builderNewBuilder39.build();
        BillingResult.Builder builderNewBuilder40 = BillingResult.newBuilder();
        builderNewBuilder40.setResponseCode(6);
        builderNewBuilder40.setDebugMessage("An error occurred while retrieving billing override.");
        zzF = builderNewBuilder40.build();
        BillingResult.Builder builderNewBuilder41 = BillingResult.newBuilder();
        builderNewBuilder41.setResponseCode(-2);
        builderNewBuilder41.setDebugMessage("Play Store version installed does not support the provided billing program.");
        zzG = builderNewBuilder41.build();
        BillingResult.Builder builderNewBuilder42 = BillingResult.newBuilder();
        builderNewBuilder42.setResponseCode(-2);
        builderNewBuilder42.setDebugMessage("Play Store version installed does not support launching external links.");
        zzH = builderNewBuilder42.build();
        BillingResult.Builder builderNewBuilder43 = BillingResult.newBuilder();
        builderNewBuilder43.setResponseCode(5);
        builderNewBuilder43.setDebugMessage("A DeveloperProvidedBillingListener must be provided when initializing the BillingClient in order to use multiple payment options for this billing program.");
        zzI = builderNewBuilder43.build();
        BillingResult.Builder builderNewBuilder44 = BillingResult.newBuilder();
        builderNewBuilder44.setResponseCode(5);
        builderNewBuilder44.setDebugMessage("A listener must be provided calling this method.");
        builderNewBuilder44.build();
        BillingResult.Builder builderNewBuilder45 = BillingResult.newBuilder();
        builderNewBuilder45.setResponseCode(-2);
        builderNewBuilder45.setDebugMessage("Play Store version installed does not support show billing program information dialog.");
        zzJ = builderNewBuilder45.build();
        BillingResult.Builder builderNewBuilder46 = BillingResult.newBuilder();
        builderNewBuilder46.setResponseCode(-2);
        builderNewBuilder46.setDebugMessage("Play Store version installed does not support get billing choice info.");
        zzK = builderNewBuilder46.build();
    }

    static BillingResult zza(int i, String str) {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.setResponseCode(i);
        builderNewBuilder.setDebugMessage(str);
        return builderNewBuilder.build();
    }
}
